import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { WebSocketProvider } from "../providers/webSocket";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WebSocketProvider>
        <body className={inter.className}>{children}</body>
      </WebSocketProvider>
    </html>
  );
}
